spring:
  application:
    name: seats_reservation

  datasource:
    url: jdbc:postgresql://localhost:5432/seats_reservation
    username: postgres
    password: ${DB_PASSWORD:korvin}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: base_schema

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: base_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog.xml
    default-schema: base_schema
    liquibase-schema: base_schema

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
